### ISSUE TITLE
Add missing dependencies and updated instructions

### ISSUE THREAD

**Issue by jonahbardos** [UTSARobotics/ros1_bootcamp#1]
You can assign this to me and I can make a PR request. I may need to be added as a collaborator to create  PR.
[README.md](https://github.com/UTSARobotics/ros1_bootcamp/files/11483288/README.md)

**Comment by jc-cr** [comment]
Thank you for creating an issue! I added a ros dep install section to Readme in 639078d

It pretty much does what you added but in an automatic, ROS specific way.
